dataset_path: data/raw

processed_path: data/processed

random_seed: 42

window_size: 30

batch_size: 64

epochs: 100

learning_rate: 0.001

datasets:
  - FD001
  - FD002
  - FD003
  - FD004

# Remaining Useful Life (RUL)
rul:
  cap_enabled: true
  cap_value: 125

# Feature Selection
feature_selection:

  remove_constant: true

  variance_threshold: 0.001

  manual_remove: []